CREATE TABLE IF NOT EXISTS product (
    id              integer generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_path        text CHECK(LENGTH(url_path) <= 150) NOT NULL,
    variant_id      integer NOT NULL REFERENCES variant,
    merchant_id     integer NOT NULL REFERENCES merchant,
    created         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_product_updated_timestamp') THEN
        CREATE TRIGGER update_product_updated_timestamp
        BEFORE UPDATE
        ON product
        FOR EACH ROW EXECUTE PROCEDURE update_updated_timestamp();
    END IF;
END
$$;
