CREATE TABLE IF NOT EXISTS merchant_page (
    id                  integer generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_path            text CHECK(LENGTH(url_path) <= 150) NOT NULL,
    should_scrape       boolean DEFAULT true,
    failed_scrape_days  smallint CHECK(failed_scrape_days >= 0) DEFAULT 0,
    merchant_id         integer NOT NULL REFERENCES merchant,
    created             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_merchant_page_updated_timestamp') THEN
        CREATE TRIGGER update_merchant_page_updated_timestamp
        BEFORE UPDATE
        ON merchant_page
        FOR EACH ROW EXECUTE PROCEDURE update_updated_timestamp();
    END IF;
END
$$;
