CREATE TABLE IF NOT EXISTS brand (
    id          integer generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text CHECK (LENGTH(name) <= 100) NOT NULL,
    url_slug    text CHECK (LENGTH(url_slug) <= 120) NOT NULL,
    created     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_brand_updated_timestamp') THEN
        CREATE TRIGGER update_brand_updated_timestamp
        BEFORE UPDATE
        ON brand
        FOR EACH ROW EXECUTE PROCEDURE update_updated_timestamp();
    END IF;
END
$$;
