CREATE TABLE IF NOT EXISTS price (
    id              integer generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    price           numeric(9, 2) NOT NULL,
    time_from       TIMESTAMP WITH TIME ZONE NOT NULL,
    time_to         TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    product_id      integer NOT NULL REFERENCES product,
    created         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_price_updated_timestamp') THEN
        CREATE TRIGGER update_price_updated_timestamp
        BEFORE UPDATE
        ON price
        FOR EACH ROW EXECUTE PROCEDURE update_updated_timestamp();
    END IF;
END
$$;
