parameters:
    merchants:
        allbeauty:
            name: 'allbeauty'
            url: 'https://www.allbeauty.com'
            sitemap_url: 'https://www.allbeauty.com/reports/google_sitemap.xml'
            sitemap_url_path_pattern: '~^\/[0-9]+-[a-z0-9-]+~'
            ignore_list_file: '/Users/mikey/code/ParfumPulse/allbeauty_ignores.json'
            use_lastmod: false

        notino:
            name: 'Notino'
            url: 'https://www.notino.co.uk'
            sitemap_url: 'https://www.notino.co.uk/export/sitemap/sitemap_detail_parfemy_uk.xml'
            ignore_list_file: '/Users/mikey/code/ParfumPulse/notino_ignores.json'
            use_lastmod: false
